# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches : [main, develop ;feature /*]

jobs:
  build:
   name: "build"
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - run: |
      ls data
      while read line
      do
      echo -e "$line\n" #instruction 
      done < listeScan.txt
